import { type NextPage } from "next";
import { Auth, ThemeSupa } from '@supabase/auth-ui-react'
import Head from "next/head";
import React from "react";
import { useSession, useSupabaseClient, useUser } from "@supabase/auth-helpers-react";
import { Layout } from "../components/layout";

const Home: NextPage = () => {
  let supabaseClient = useSupabaseClient()
  const user = useUser();
        
  const session = useSession()

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#ffffff] to-[#e4d1ff]">
        <Layout session={session}>
          {(!user) ?
            <Auth redirectTo="http://localhost:3000/" appearance={{ theme: ThemeSupa }} supabaseClient={supabaseClient} providers={['google']} socialLayout="horizontal"/>
            :
            <>
              <div className="p-4 bg-white rounded-full select-none cursor-pointer shadow-md active:translate-y-0.5"> Create a class </div>
              <div className="p-4 bg-white rounded-full select-none cursor-pointer shadow-md active:translate-y-0.5"> Join a class </div>
              <div className="p-4 bg-white rounded-full select-none cursor-pointer shadow-md active:translate-y-0.5" onClick={() => supabaseClient.auth.signOut()}>Sign out</div>
            </>
          }
          
        </Layout>
      </main>
    </>
  );
};

export default Home;