import { type NextPage } from "next";
import Head from "next/head";
import React from "react";
import { useSession } from "@supabase/auth-helpers-react";
import { Layout } from "../components/Layout";
import Reaction from "../components/Reaction";
import Message from "../components/Message";

const Home: NextPage = () => {
        
  const session = useSession()

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#ffffff] to-[#e4d1ff]">
        <Layout session={session}>
          <div className="flex flex-col justify-center items-center w-24 h-fit gap-4">
            <div className="grid grid-cols-2 gap-2 w-fit">
              <Reaction>👍</Reaction>
              <Reaction>👎</Reaction>
              <Reaction>😲</Reaction>
              <Reaction>🤔</Reaction>
              <Reaction>🎉</Reaction>
              <Reaction>👏</Reaction>
            </div>
            <Message/>
          </div>
        </Layout>
      </main>
    </>
  );
};

export default Home;